/**
 * Embedded-font helper for planner SVG drawings.
 *
 * Vercel's serverless runtime ships no system fonts, so SVG text rendered
 * through sharp/librsvg comes out as tofu boxes. This module base64-embeds
 * subsetted DejaVu (open-licensed) directly into the SVG via @font-face, so
 * text renders identically everywhere.
 *
 * The font data is inlined into the JS bundle at build time
 * (lib/planner-font-data.ts, generated by scripts/gen-font-data.py) because
 * Vercel serverless functions cannot read files from public/ at runtime.
 *
 * Usage: insert `svgFontStyle()` right after the opening `<svg ...>` tag,
 * and use font-family="DejaVu Sans" / "DejaVu Sans Mono" in <text> elements.
 * (Generic "sans-serif"/"monospace" fall back to nothing on Vercel.)
 */
import {
  DEJAVUSANS_B64,
  DEJAVUSANS_BOLD_B64,
  DEJAVUSANSMONO_B64,
} from "./planner-font-data";

function fontFace(family: string, b64: string, weight: string): string {
  return `@font-face{font-family:"${family}";font-weight:${weight};src:url(data:font/ttf;base64,${b64}) format("truetype");}`;
}

const CACHED =
  `<style>` +
  fontFace("DejaVu Sans", DEJAVUSANS_B64, "normal") +
  fontFace("DejaVu Sans", DEJAVUSANS_BOLD_B64, "bold") +
  fontFace("DejaVu Sans Mono", DEJAVUSANSMONO_B64, "normal") +
  `</style>`;

export function svgFontStyle(): string {
  return CACHED;
}
