#!/usr/bin/env python3
"""Regenerate lib/planner-font-data.ts with subsetted DejaVu fonts.

Reads the full DejaVu TTFs from public/fonts/, subsets them to the glyphs
the shop drawings actually use (keeps the bundle small), and writes them
as base64 constants. Run from the repo root:

    python3 scripts/gen-font-data.py
"""
import base64
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FONTS = ["DejaVuSans", "DejaVuSans-Bold", "DejaVuSansMono"]
UNICODES = "U+0020-007E,U+00A0-00FF,U+2013-2014,U+2018-2019,U+201C-201D,U+2022,U+2032-2033,U+2190-2193"


def main() -> None:
    out: dict[str, str] = {}
    for name in FONTS:
        src = ROOT / "public" / "fonts" / f"{name}.ttf"
        if not src.exists():
            print(f"missing: {src}", file=sys.stderr)
            sys.exit(1)
        tmp = ROOT / f".{name}-subset.ttf"
        subprocess.run(
            [
                sys.executable, "-m", "fontTools.subset", str(src),
                f"--output-file={tmp}",
                f"--unicodes={UNICODES}",
                "--layout-features=", "--no-hinting", "--desubroutinize",
            ],
            check=True,
        )
        out[name] = base64.b64encode(tmp.read_bytes()).decode()
        tmp.unlink()

    dest = ROOT / "lib" / "planner-font-data.ts"
    lines = [
        "// AUTO-GENERATED by scripts/gen-font-data.py — subsetted DejaVu fonts for SVG embedding.",
        "// Do not edit by hand. Regenerate with: python3 scripts/gen-font-data.py",
        "",
    ]
    for name, b64 in out.items():
        const = name.replace("-", "_").upper() + "_B64"
        lines.append(f'export const {const} = "{b64}";')
    dest.write_text("\n".join(lines) + "\n")
    print(f"wrote {dest} ({dest.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
